// Mocks generated by Mockito 5.4.4 from annotations
// in vania/test/src/authentication/jwt/jwt_signer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vania/src/authentication/token_handler/jwt/jwt_config.dart'
    as _i3;
import 'package:vania/src/env_handler/env_interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIEnv_0 extends _i1.SmartFake implements _i2.IEnv {
  _FakeIEnv_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JwtConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtConfig extends _i1.Mock implements _i3.JwtConfig {
  MockJwtConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IEnv get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _FakeIEnv_0(
          this,
          Invocation.getter(#env),
        ),
      ) as _i2.IEnv);

  @override
  String get secretKey => (super.noSuchMethod(
        Invocation.getter(#secretKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#secretKey),
        ),
      ) as String);

  @override
  String get audience => (super.noSuchMethod(
        Invocation.getter(#audience),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#audience),
        ),
      ) as String);
}
