name: basic_authentication
description: A minimal token-based authentication example built with the Vania framework.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  vania:
    path: ../../packages/core
  vania_mysql:
    path: ../../packages/vania_mysql
  vania_auth:
    path: ../../packages/vania_auth

dependency_overrides:
  vania:
    path: ../../packages/core
  vania_auth:
    path: ../../packages/vania_auth
  vania_mysql:
    path: ../../packages/vania_mysql

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
