// Mocks generated by Mockito 5.4.4 from annotations
// in vania/test/src/authentication/authenticate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:vania/src/authentication/authentication_manager.dart' as _i2;
import 'package:vania/vania.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationManager_0 extends _i1.SmartFake
    implements _i2.AuthenticationManager {
  _FakeAuthenticationManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpRequest_1 extends _i1.SmartFake implements _i3.HttpRequest {
  _FakeHttpRequest_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_2 extends _i1.SmartFake implements Uri {
  _FakeUri_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpResponse_3 extends _i1.SmartFake implements _i3.HttpResponse {
  _FakeHttpResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequest_4 extends _i1.SmartFake implements _i4.Request {
  _FakeRequest_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationManager extends _i1.Mock
    implements _i2.AuthenticationManager {
  MockAuthenticationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthorized => (super.noSuchMethod(
        Invocation.getter(#isAuthorized),
        returnValue: false,
      ) as bool);

  @override
  _i2.AuthenticationManager guard(String? guard) => (super.noSuchMethod(
        Invocation.method(
          #guard,
          [guard],
        ),
        returnValue: _FakeAuthenticationManager_0(
          this,
          Invocation.method(
            #guard,
            [guard],
          ),
        ),
      ) as _i2.AuthenticationManager);

  @override
  _i2.AuthenticationManager login(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [user],
        ),
        returnValue: _FakeAuthenticationManager_0(
          this,
          Invocation.method(
            #login,
            [user],
          ),
        ),
      ) as _i2.AuthenticationManager);

  @override
  dynamic get(String? field) => super.noSuchMethod(Invocation.method(
        #get,
        [field],
      ));

  @override
  _i5.Future<Map<String, dynamic>> createToken({
    Duration? expiresIn,
    bool? withRefreshToken = false,
    bool? customToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [],
          {
            #expiresIn: expiresIn,
            #withRefreshToken: withRefreshToken,
            #customToken: customToken,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> createTokenByRefreshToken(
    String? token, {
    Duration? expiresIn,
    bool? customToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTokenByRefreshToken,
          [token],
          {
            #expiresIn: expiresIn,
            #customToken: customToken,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> deleteTokens() => (super.noSuchMethod(
        Invocation.method(
          #deleteTokens,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteCurrentToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentToken,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> check(
    String? token, {
    Map<String, dynamic>? user,
    bool? isCustomToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #check,
          [token],
          {
            #user: user,
            #isCustomToken: isCustomToken,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [Request].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequest extends _i1.Mock implements _i4.Request {
  MockRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HttpRequest get request => (super.noSuchMethod(
        Invocation.getter(#request),
        returnValue: _FakeHttpRequest_1(
          this,
          Invocation.getter(#request),
        ),
      ) as _i3.HttpRequest);

  @override
  Map<String, dynamic> get body => (super.noSuchMethod(
        Invocation.getter(#body),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set body(Map<String, dynamic>? _body) => super.noSuchMethod(
        Invocation.setter(
          #body,
          _body,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_2(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  _i3.HttpResponse get response => (super.noSuchMethod(
        Invocation.getter(#response),
        returnValue: _FakeHttpResponse_3(
          this,
          Invocation.getter(#response),
        ),
      ) as _i3.HttpResponse);

  @override
  Map<String, dynamic> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  T? cookie<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #cookie,
        [key],
      )) as T?);

  @override
  _i5.Future<_i4.Request> extractBody() => (super.noSuchMethod(
        Invocation.method(
          #extractBody,
          [],
        ),
        returnValue: _i5.Future<_i4.Request>.value(_FakeRequest_4(
          this,
          Invocation.method(
            #extractBody,
            [],
          ),
        )),
      ) as _i5.Future<_i4.Request>);

  @override
  Map<String, dynamic> all() => (super.noSuchMethod(
        Invocation.method(
          #all,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> params() => (super.noSuchMethod(
        Invocation.method(
          #params,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool isMethod(String? method) => (super.noSuchMethod(
        Invocation.method(
          #isMethod,
          [method],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> only(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #only,
          [keys],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool has(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasAny(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #hasAny,
          [keys],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<dynamic> whenHas(String? key) => (super.noSuchMethod(
        Invocation.method(
          #whenHas,
          [key],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  Map<String, dynamic> except(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #except,
          [key],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.RequestFile? file(String? key) => (super.noSuchMethod(Invocation.method(
        #file,
        [key],
      )) as _i4.RequestFile?);

  @override
  List<_i4.RequestFile>? files(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #files,
        [key],
      )) as List<_i4.RequestFile>?);

  @override
  String string(String? key) => (super.noSuchMethod(
        Invocation.method(
          #string,
          [key],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #string,
            [key],
          ),
        ),
      ) as String);

  @override
  int? integer(String? key) => (super.noSuchMethod(Invocation.method(
        #integer,
        [key],
      )) as int?);

  @override
  double? asDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #asDouble,
        [key],
      )) as double?);

  @override
  bool boolean(String? key) => (super.noSuchMethod(
        Invocation.method(
          #boolean,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  DateTime? date(String? key) => (super.noSuchMethod(Invocation.method(
        #date,
        [key],
      )) as DateTime?);

  @override
  void merge(Map<String, dynamic>? values) => super.noSuchMethod(
        Invocation.method(
          #merge,
          [values],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeIfMissing(Map<String, dynamic>? values) => super.noSuchMethod(
        Invocation.method(
          #mergeIfMissing,
          [values],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? header(
    String? key, [
    String? defaultHeader,
  ]) =>
      (super.noSuchMethod(Invocation.method(
        #header,
        [
          key,
          defaultHeader,
        ],
      )) as String?);

  @override
  bool isFormData() => (super.noSuchMethod(
        Invocation.method(
          #isFormData,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isJson() => (super.noSuchMethod(
        Invocation.method(
          #isJson,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isUrlencoded() => (super.noSuchMethod(
        Invocation.method(
          #isUrlencoded,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void validate(
    dynamic rules, [
    Map<String, String>? messages = const {},
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #validate,
          [
            rules,
            messages,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
