// Mocks generated by Mockito 5.4.4 from annotations
// in vania/test/src/authentication/authentication_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vania/src/authentication/token_handler/token_handler.dart'
    as _i2;
import 'package:vania/src/authentication/user_repository.dart' as _i3;
import 'package:vania/src/config/config.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenHandler_0 extends _i1.SmartFake implements _i2.TokenHandler {
  _FakeTokenHandler_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TokenHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenHandler extends _i1.Mock implements _i2.TokenHandler {
  MockTokenHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenHandler setPayload(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPayload,
          [payload],
        ),
        returnValue: _FakeTokenHandler_0(
          this,
          Invocation.method(
            #setPayload,
            [payload],
          ),
        ),
      ) as _i2.TokenHandler);

  @override
  Map<String, dynamic> createToken({
    String? guard = r'',
    Duration? expiresIn,
    bool? withRefreshToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [],
          {
            #guard: guard,
            #expiresIn: expiresIn,
            #withRefreshToken: withRefreshToken,
          },
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> refreshToken(
    String? token,
    String? guard,
    Duration? expiresIn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [
            token,
            guard,
            expiresIn,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> verify(
    String? token,
    String? guard,
    String? expectedType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [
            token,
            guard,
            expectedType,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> storeToken({
    required String? name,
    required String? userId,
    required String? token,
    required DateTime? createdAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [],
          {
            #name: name,
            #userId: userId,
            #token: token,
            #createdAt: createdAt,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> findUserByToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserByToken,
          [token],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> deleteTokenById(
    String? userId, [
    DateTime? deletedAt,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTokenById,
          [
            userId,
            deletedAt,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTokenByToken(
    String? token, [
    DateTime? deletedAt,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTokenByToken,
          [
            token,
            deletedAt,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i5.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set setApplicationConfig(Map<String, dynamic>? conf) => super.noSuchMethod(
        Invocation.setter(
          #setApplicationConfig,
          conf,
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic get(String? key) => super.noSuchMethod(Invocation.method(
        #get,
        [key],
      ));
}
