// Mocks generated by Mockito 5.4.4 from annotations
// in vania/test/src/authentication/jwt_token_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:vania/src/authentication/token_handler/jwt/jwt_config.dart'
    as _i2;
import 'package:vania/src/authentication/token_handler/jwt/jwt_signer.dart'
    as _i3;
import 'package:vania/src/authentication/token_handler/jwt/jwt_verifier.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJwtConfig_0 extends _i1.SmartFake implements _i2.JwtConfig {
  _FakeJwtConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JwtSigner].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtSigner extends _i1.Mock implements _i3.JwtSigner {
  MockJwtSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JwtConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeJwtConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.JwtConfig);

  @override
  Map<String, dynamic> createToken({
    required Map<String, dynamic>? payload,
    String? guard = r'',
    Duration? expiresIn = const Duration(hours: 1),
    bool? withRefreshToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [],
          {
            #payload: payload,
            #guard: guard,
            #expiresIn: expiresIn,
            #withRefreshToken: withRefreshToken,
          },
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [JwtVerifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtVerifier extends _i1.Mock implements _i4.JwtVerifier {
  MockJwtVerifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JwtConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeJwtConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.JwtConfig);

  @override
  Map<String, dynamic> verify(
    String? token,
    String? guard,
    String? expectedType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [
            token,
            guard,
            expectedType,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
