// Mocks generated by Mockito 5.4.4 from annotations
// in vania/test/src/authentication/token_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:vania/src/env_handler/env.dart' as _i3;
import 'package:vania/src/env_handler/env_loader_interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIEnvLoader_0 extends _i1.SmartFake implements _i2.IEnvLoader {
  _FakeIEnvLoader_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Env].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnv extends _i1.Mock implements _i3.Env {
  MockEnv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IEnvLoader get envLoader => (super.noSuchMethod(
        Invocation.getter(#envLoader),
        returnValue: _FakeIEnvLoader_0(
          this,
          Invocation.getter(#envLoader),
        ),
      ) as _i2.IEnvLoader);

  @override
  Map<String, String> get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set env(Map<String, String>? _env) => super.noSuchMethod(
        Invocation.setter(
          #env,
          _env,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void load({_i4.File? file}) => super.noSuchMethod(
        Invocation.method(
          #load,
          [],
          {#file: file},
        ),
        returnValueForMissingStub: null,
      );

  @override
  T get<T>(
    String? key, [
    dynamic defaultValue,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [
              key,
              defaultValue,
            ],
          ),
        ),
      ) as T);
}
