name: elasticsearch_search
description: A small full-text search API using vania_elasticsearch with the Vania framework.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  vania:
    path: ../../packages/core
  vania_elasticsearch:
    path: ../../packages/vania_elasticsearch

dependency_overrides:
  vania:
    path: ../../packages/core
  vania_elasticsearch:
    path: ../../packages/vania_elasticsearch

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
